# https://github.com/DavidAnson/markdownlint#rules--aliases

# ul-indent - Unordered list indentation
MD007: false

# no-hard-tabs - Hard tabs
MD010: false

# line-length - Line length
MD013: false

# no-duplicate-heading - Multiple headings with the same content
MD024: false

# single-title/single-h1 - Multiple top-level headings in the same document
MD025: false

# no-trailing-punctuation - Trailing punctuation in heading
MD026: false

# ol-prefix - Ordered list item prefix
MD029: false

# no-inline-html - Inline HTML
MD033: false

# no-bare-urls - Bare URL used
MD034: false

# no-emphasis-as-heading - Emphasis used instead of a heading
MD036: false

# fenced-code-language - Fenced code blocks should have a language specified
MD040: false

# first-line-heading/first-line-h1 - First line in a file should be a top-level heading
MD041: false

# code-block-style - Code block style
MD046: false
